### PR TITLE
Workaround for issue #9

### PR DESCRIPTION
**Pull request by peterjpxie**
Take only basename if it is a Windows full path with colon (:), e.g. D:\a\b.txt -> b.txt

### CODE REVIEW

**Comment by shibayu36** [comment]
What is the status of this PR?  Do you want to merge it to this repository in the future?  or do you want to fork and release as another extension?

**Comment by peterjpxie** [comment]
It is in open state. I thought you would review and merge it. It is my first PR in github, so I am not sure about the process.

**Comment by shibayu36** [comment]
> It is my first PR in github

Great!


At first, I cannot merge this PR because there are changes that are not related to workaround.  So please remove unrelated changes.  I think you should only change `src/extension.ts` to fix issue #9 .

If you want to fork and release it as another extension, it's better to work somewhere else than this PR.  For example

* Make branch in your forked repository, and fix #9, and send pull request to my repository
* Make another branch in your forked repository, and change code for another release.  You don't need to send pull request to my repository
    * If you don't want to release it as a separate extension, you don't need to do this of course!

**Comment by peterjpxie** [comment]
Okay... only 1st commit 8b32a9430cafe9e5f9c8634436bd36b8a6cad080 was required for this workaround. When I raised this PR, only this commit was made. Later on, I added something else to create my own extension and did not expect it would include later changes. Ignore this PR and I would leave it to you to decide what to change. I don't want to roll back my master branch. 
Thank you!

**Pull request closed without merging**
